#!/usr/bin/env python3
"""Sync gallery.json from a public Google Drive folder.

Reads the folder's image files via the Google Drive API and writes their
ids/names/dimensions to gallery.json. The website derives the actual
thumbnail/full-size image URLs from each photo's id at render time
(see driveImageUrl() in script.js), so this file only needs to track
which files exist.

This is meant to run inside .github/workflows/sync-gallery.yml, where
GOOGLE_DRIVE_API_KEY is a GitHub Actions secret (never exposed to the
site itself) and GALLERY_FOLDER_ID is read from gallery.json unless
overridden.

Usage:
    GOOGLE_DRIVE_API_KEY=... python sync_gallery.py [folder_id]
"""
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).parent
GALLERY_JSON = ROOT / "gallery.json"
DRIVE_API_URL = "https://www.googleapis.com/drive/v3/files"


def list_images(folder_id, api_key):
    files = []
    page_token = None
    query = f"'{folder_id}' in parents and mimeType contains 'image/' and trashed = false"
    while True:
        params = {
            "q": query,
            "key": api_key,
            "fields": "nextPageToken, files(id,name,imageMediaMetadata)",
            "orderBy": "name",
            "pageSize": 1000,
        }
        if page_token:
            params["pageToken"] = page_token
        url = DRIVE_API_URL + "?" + urllib.parse.urlencode(params)
        try:
            with urllib.request.urlopen(url) as resp:
                data = json.load(resp)
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", errors="replace")
            raise SystemExit(f"Drive API request failed ({e.code}): {body}")
        files.extend(data.get("files", []))
        page_token = data.get("nextPageToken")
        if not page_token:
            break
    return files


def main():
    api_key = os.environ.get("GOOGLE_DRIVE_API_KEY")
    if not api_key:
        raise SystemExit("GOOGLE_DRIVE_API_KEY is not set")

    existing = json.loads(GALLERY_JSON.read_text(encoding="utf-8")) if GALLERY_JSON.exists() else {}
    folder_id = (
        os.environ.get("GALLERY_FOLDER_ID")
        or (sys.argv[1] if len(sys.argv) > 1 else None)
        or existing.get("folderId")
    )
    if not folder_id:
        raise SystemExit("No folder id: set GALLERY_FOLDER_ID, pass it as an argument, or set 'folderId' in gallery.json")

    files = list_images(folder_id, api_key)
    photos = []
    for f in files:
        meta = f.get("imageMediaMetadata") or {}
        photos.append({
            "id": f["id"],
            "name": f.get("name", ""),
            "width": meta.get("width"),
            "height": meta.get("height"),
        })

    data = {
        "_readme": existing.get("_readme") or (
            "Auto-generated by .github/workflows/sync-gallery.yml from the public Google Drive "
            "folder linked in the Gallery section of index.html. Do not edit by hand — it gets "
            "overwritten on the next sync. To add/remove photos, just add/remove them in the "
            "Drive folder, then either wait for the next scheduled sync or run the 'Sync photo "
            "gallery' workflow manually from the Actions tab."
        ),
        "folderId": folder_id,
        "updatedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "photos": photos,
    }
    GALLERY_JSON.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(photos)} photo(s) to {GALLERY_JSON}")


if __name__ == "__main__":
    main()
